import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { buildFixtures } from "./fixtures.js";
import { REASON_CODES } from "./reason-codes.js";
import { VECTOR_SCHEMA, validateVectorOrThrow } from "./schema.js";
import { buildAllVectors } from "./topics.js";

export async function authorAllVectors(outputDir: string): Promise<string[]> {
  const fixtures = buildFixtures();
  const vectors = await buildAllVectors(fixtures);
  const written: string[] = [];

  await removeRetiredVectors(
    outputDir,
    new Set(vectors.map(({ relativePath }) => relativePath)),
  );

  await writeJson(join(outputDir, "fixtures.json"), fixtures);
  await writeJson(join(outputDir, "schema", "vector.schema.json"), VECTOR_SCHEMA);
  await writeJson(join(outputDir, "schema", "reason-codes.json"), { reason_codes: REASON_CODES });
  await writeReasonCodesMarkdown(join(outputDir, "schema", "reason-codes.md"));

  for (const { relativePath, vector } of vectors) {
    validateVectorOrThrow(vector);
    await writeJson(join(outputDir, relativePath), vector);
    written.push(relativePath);
  }

  return written.sort();
}

async function removeRetiredVectors(
  outputDir: string,
  expected: ReadonlySet<string>,
): Promise<void> {
  for (const path of await jsonFiles(outputDir)) {
    const relativePath = relative(outputDir, path);
    if (relativePath === "fixtures.json"
      || relativePath.startsWith("schema/")
      || relativePath.startsWith("coverage/")
      || expected.has(relativePath)) {
      continue;
    }
    let value: unknown;
    try {
      value = JSON.parse(await readFile(path, "utf8"));
    } catch {
      continue;
    }
    if (typeof value === "object" && value !== null && "vector_id" in value) {
      await unlink(path);
    }
  }
}

async function jsonFiles(root: string): Promise<string[]> {
  const files: string[] = [];
  let entries;
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch {
    return files;
  }
  for (const entry of entries) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) files.push(...await jsonFiles(path));
    else if (entry.isFile() && entry.name.endsWith(".json")) files.push(path);
  }
  return files;
}

async function writeJson(path: string, value: unknown): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

async function writeReasonCodesMarkdown(path: string): Promise<void> {
  const rows = REASON_CODES.map(
    (reason) => `| \`${reason.code}\` | ${reason.owner} | ${reason.status} | \`${reason.first_version}\` | ${reason.spec_refs.join(", ")} | ${reason.description} |`,
  ).join("\n");
  await mkdir(dirname(path), { recursive: true });
  await writeFile(
    path,
    `# Reason codes\n\n` +
      "Generated compatibility projection. The authoritative allocation container is `docs/spec/registry/reason-codes.json`; do not edit this file by hand. `reason_code` values are conformance-test vocabulary and implementations do not need to emit these strings on the wire.\n\n" +
      "| Code | Owner | Status | First version | Spec refs | Meaning |\n" +
      "|---|---|---|---|---|---|\n" +
      `${rows}\n`,
    "utf8",
  );
}
