import { sha256 } from "@noble/hashes/sha2";
import { bytesToHex, hexToBytes, utf8Bytes } from "./hex.js";
import { DoubleRatchetSession, type NdrRumor, type NdrSession, type NdrVerifiedEvent } from "./ndr.js";
import { getPublicKey } from "./nostr.js";
import { consumeVector } from "./vector-helpers.js";
import type { Fixtures } from "./fixtures.js";
import type { AuthoredVector } from "./types.js";

// Full double-ratchet transcript vector, generated by driving the published
// iris wire library (nostr-double-ratchet@0.0.138, exact-pinned in
// package.json; https://github.com/irislib/nostr-double-ratchet, MIT) under a
// deterministic RNG and clock. Conformance consumers replay the RECEIVE side:
// given the pinned session-setup secrets and outer events, a conforming
// implementation must recover the inner rumors. Byte-exact regeneration of
// the outer events additionally requires this generator's DRBG and the
// library's internal draw order; that is a generator implementation detail,
// not a conformance requirement.

const DRBG_LABEL = "heterodyne-dm-transcript-v1";
const ALICE_SESSION_SK = "a1".repeat(32);
const BOB_SESSION_SK = "b2".repeat(32);
const SHARED_SECRET = "c3".repeat(32);

export type DmTranscriptMessage = {
  seq: number;
  sender: "alice" | "bob";
  plaintext: string;
  inner_rumor: Record<string, unknown>;
  outer_event: {
    id: string;
    pubkey: string;
    created_at: number;
    kind: number;
    tags: string[][];
    content: string;
    sig: string;
  };
  header_plaintext: {
    number: number;
    nextPublicKey: string;
    previousChainLength: number;
  };
  ratchet_epoch: number;
  chain_index: number;
};

export type RatchetKeypair = {
  epoch: number;
  secret_key: string;
  public_key: string;
};

export type DmTranscript = {
  alice_session_sk: string;
  alice_session_pubkey: string;
  bob_session_sk: string;
  bob_session_pubkey: string;
  shared_secret: string;
  // DH ratchet keys each party generated during the transcript, pinned so a
  // conforming implementation can inject them where it would otherwise draw
  // fresh ratchet keys (the standard Double Ratchet test-vector seam).
  ratchet_keys: { alice: RatchetKeypair[]; bob: RatchetKeypair[] };
  messages: DmTranscriptMessage[];
  // Rumors returned by receiveEvent() during generation, in seq order; they
  // must equal messages[seq].inner_rumor.
  received_rumors: Array<Record<string, unknown> | undefined>;
};

function makeDrbg(label: string): <T extends ArrayBufferView | null>(array: T) => T {
  let counter = 0;
  return <T extends ArrayBufferView | null>(array: T): T => {
    if (!array) return array;
    const bytes = new Uint8Array(array.buffer, array.byteOffset, array.byteLength);
    let offset = 0;
    while (offset < bytes.length) {
      const block = sha256(utf8Bytes(`${label}|${counter++}`));
      const take = Math.min(block.length, bytes.length - offset);
      bytes.set(block.subarray(0, take), offset);
      offset += take;
    }
    return array;
  };
}

export function withDeterministicEnv<T>(baseSeconds: number, fn: () => T): T {
  const cryptoObject = globalThis.crypto as Crypto;
  const originalGetRandomValues = cryptoObject.getRandomValues;
  const originalNow = Date.now;
  let nowMs = baseSeconds * 1000;
  try {
    Object.defineProperty(cryptoObject, "getRandomValues", {
      value: makeDrbg(DRBG_LABEL),
      configurable: true,
      writable: true,
    });
    Date.now = () => {
      const value = nowMs;
      nowMs += 1000;
      return value;
    };
    return fn();
  } finally {
    Object.defineProperty(cryptoObject, "getRandomValues", {
      value: originalGetRandomValues,
      configurable: true,
      writable: true,
    });
    Date.now = originalNow;
  }
}

function nextRatchetKey(session: NdrSession, epoch: number): RatchetKeypair {
  const key = session.state.ourNextNostrKey;
  return {
    epoch,
    secret_key: bytesToHex(key.privateKey),
    public_key: key.publicKey,
  };
}

export function generateDmTranscript(fixtures: Fixtures): DmTranscript {
  const T = fixtures.test_epoch;
  const alicePub = getPublicKey(ALICE_SESSION_SK);
  const bobPub = getPublicKey(BOB_SESSION_SK);
  const aliceDevice = fixtures.device_publishing_keys.alice_device_1;
  const bobDevice = fixtures.device_publishing_keys.bob_device_1;
  const aliceNpub = fixtures.personas.alice.cold_root.pubkey;
  const bobNpub = fixtures.personas.bob.cold_root.pubkey;

  return withDeterministicEnv(T + 200, () => {
    const alice = DoubleRatchetSession.init(bobPub, hexToBytes(ALICE_SESSION_SK), true, hexToBytes(SHARED_SECRET), "alice");
    const bob = DoubleRatchetSession.init(alicePub, hexToBytes(BOB_SESSION_SK), false, hexToBytes(SHARED_SECRET), "bob");

    const messages: DmTranscriptMessage[] = [];
    let seq = 0;

    const record = (
      session: NdrSession,
      sender: "alice" | "bob",
      plaintext: string,
      ratchetEpoch: number,
      chainIndex: number,
      previousChainLength: number,
    ) => {
      const devicePubkey = sender === "alice" ? aliceDevice.pubkey : bobDevice.pubkey;
      const peerNpub = sender === "alice" ? bobNpub : aliceNpub;
      const { event, innerEvent } = session.sendEvent({
        kind: 14,
        pubkey: devicePubkey,
        tags: [["p", peerNpub]],
        content: plaintext,
      });
      messages.push({
        seq: seq++,
        sender,
        plaintext,
        inner_rumor: innerEvent as unknown as Record<string, unknown>,
        outer_event: event as DmTranscriptMessage["outer_event"],
        header_plaintext: {
          number: chainIndex,
          nextPublicKey: session.state.ourNextNostrKey.publicKey,
          previousChainLength,
        },
        ratchet_epoch: ratchetEpoch,
        chain_index: chainIndex,
      });
      return event;
    };

    const receivedRumors: Array<Record<string, unknown> | undefined> = [];
    const receive = (session: NdrSession, event: NdrVerifiedEvent) => {
      receivedRumors.push(session.receiveEvent(event) as unknown as Record<string, unknown> | undefined);
    };

    // Alice draws her epoch-1 ratchet key inside Session.init (initiator).
    const aliceEpoch1 = nextRatchetKey(alice, 1);

    const a1 = record(alice, "alice", "Hey Bob - first message over the core DM ratchet.", 0, 0, 0);
    const a2 = record(alice, "alice", "Second message in the same sending chain.", 0, 1, 0);
    receive(bob, a1);
    // Bob's first receive ran his DH ratchet, drawing his epoch-1 key.
    const bobEpoch1 = nextRatchetKey(bob, 1);
    receive(bob, a2);
    const b1 = record(bob, "bob", "Hi Alice - Bob's first reply triggers a DH ratchet.", 0, 0, 0);
    receive(alice, b1);
    const aliceEpoch2 = nextRatchetKey(alice, 2);
    const a3 = record(alice, "alice", "Alice again after one full round trip.", 1, 0, 2);
    receive(bob, a3);
    const bobEpoch2 = nextRatchetKey(bob, 2);
    const b2 = record(bob, "bob", "Bob after a second DH ratchet step.", 1, 0, 1);
    receive(alice, b2);

    return {
      alice_session_sk: ALICE_SESSION_SK,
      alice_session_pubkey: alicePub,
      bob_session_sk: BOB_SESSION_SK,
      bob_session_pubkey: bobPub,
      shared_secret: SHARED_SECRET,
      ratchet_keys: {
        alice: [aliceEpoch1, aliceEpoch2],
        bob: [bobEpoch1, bobEpoch2],
      },
      messages,
      received_rumors: receivedRumors,
    };
  });
}

export function buildDmTranscriptVectors(fixtures: Fixtures): AuthoredVector[] {
  const transcript = generateDmTranscript(fixtures);
  const aliceDevice = fixtures.device_publishing_keys.alice_device_1;
  const bobDevice = fixtures.device_publishing_keys.bob_device_1;

  return [
    consumeVector("dm/006-double-ratchet-transcript.json", {
      vector_id: "dm/double-ratchet-transcript",
      spec_refs: ["§5.7.1", "§5.7.3", "§9.5", "§14.3"],
      description:
        "Full five-message double-ratchet transcript (alice x2 in one sending chain, bob reply, alice after a DH ratchet, bob after a second DH ratchet) produced by the pinned upstream wire library from the pinned session-setup secrets; a conforming receiver replays the outer events in delivery order and must recover every inner rumor.",
      input: {
        wire_library: "nostr-double-ratchet@0.0.138 (https://github.com/irislib/nostr-double-ratchet)",
        alice_session_sk: transcript.alice_session_sk,
        alice_session_pubkey: transcript.alice_session_pubkey,
        alice_device_publishing_key: aliceDevice.pubkey,
        bob_session_sk: transcript.bob_session_sk,
        bob_session_pubkey: transcript.bob_session_pubkey,
        bob_device_publishing_key: bobDevice.pubkey,
        shared_secret: transcript.shared_secret,
        initiator: "alice",
        ratchet_keys: transcript.ratchet_keys,
        delivery_order: transcript.messages.map((m) => ({
          seq: m.seq,
          sender: m.sender,
          outer_event: m.outer_event,
        })),
      },
      expected_output: {
        verdict: "accept",
        messages: transcript.messages.map((m) => ({
          seq: m.seq,
          sender: m.sender,
          inner_rumor: m.inner_rumor,
          header_plaintext: m.header_plaintext,
          outer_signer: m.outer_event.pubkey,
          ratchet_epoch: m.ratchet_epoch,
          chain_index: m.chain_index,
        })),
        outer_signer_rotation: {
          alice: [...new Set(transcript.messages.filter((m) => m.sender === "alice").map((m) => m.outer_event.pubkey))],
          bob: [...new Set(transcript.messages.filter((m) => m.sender === "bob").map((m) => m.outer_event.pubkey))],
        },
        properties: {
          same_chain_messages_share_outer_signer: true,
          dh_ratchet_rotates_outer_signer: true,
          outer_signer_is_current_ratchet_key: true,
          epoch_zero_outer_signers_are_session_pubkeys: true,
        },
      },
      decision_trace: [
        "init_responder_session_from_pinned_secrets",
        "decrypt_header_with_current_or_next_key",
        "advance_symmetric_chain_within_epoch",
        "dh_ratchet_on_new_header_key",
        "recover_inner_rumors_in_order",
      ],
      notes:
        "Generated by driving nostr-double-ratchet@0.0.138 (irislib, MIT; the production iris wire library) with the pinned session-setup secrets under a deterministic RNG (label heterodyne-dm-transcript-v1) and a Date.now() counter starting at (test_epoch+200)s advancing 1s per call, so the suite regenerates it byte-for-byte. Conformance is receive-side: replaying the outer events in delivery order through both sessions must yield these inner rumors. input.ratchet_keys pins the DH ratchet keys each party generated during the transcript (epoch 1 = alice's Session.init draw / bob's first-receive ratchet, epoch 2 = each party's next ratchet); implementations under test inject them where they would otherwise draw fresh ratchet keys - the standard Double Ratchet test-vector seam - because post-ratchet messages are undecryptable without them. Each pinned public_key equals the nextPublicKey advertised in that party's prior-chain headers and (for epoch 1) the outer signer of that party's post-ratchet messages. The outer signer is the sender's CURRENT ratchet key, rotated per DH ratchet step, NOT per message: seq 0 and 1 share alice's epoch-0 signer (her session pubkey), seq 3 uses her epoch-1 signer. Relays therefore cannot link outer events to a persona, but CAN link same-epoch messages to each other (5.7.1, 9.5). Inner rumors are unsigned kind:14 with id, pubkey = the sender's device publishing key bound to the persona via kind:31001 (5.7.2).",
    }),
  ];
}
