import { consumeVector } from "./vector-helpers.js";
import type { AuthoredVector } from "./types.js";
import {
  evaluateAllowance,
  evaluateAuthorization,
  evaluateFreshness,
  evaluateGrantActivation,
  evaluateJointGovernance,
  evaluateKeyRequest,
  evaluatePrivateProjection,
  evaluateRoleLeafChange,
  evaluateWorkspaceObject,
  eventsAreByteIdentical,
  resolveEffectiveHosts,
  selectEventRepository,
  signWorkspaceObject,
  workspaceObjectId,
} from "./workspace.js";

const H64 = "11".repeat(32);
const H64_B = "22".repeat(32);
const H40 = "33".repeat(20);
const SECRET = "01".repeat(32);

const vector = (
  path: string,
  vector_id: string,
  description: string,
  input: Record<string, unknown>,
  expected_output: Record<string, unknown>,
): AuthoredVector => consumeVector(path, {
  vector_id,
  spec_refs: ["canonical anchor supplied by vector metadata"],
  description,
  input,
  expected_output,
});

export function buildWorkspaceVectors(): AuthoredVector[] {
  const signedManifest = signWorkspaceObject({
    spec_version: "heterodyne/0.5.0",
    object_type: "workspace-manifest-v1",
    workspace_id: H64,
    kel_head: H64,
    authority_sequence: 4,
    repository_rid: "rad:zWorkspace",
    repository_head: H40,
    issued_at: 1_720_000_000,
    root_policy_rid: "rad:zPolicy",
    root_policy_head: H64_B,
    visibility: "public",
    public_roles: [],
  }, SECRET);
  const manifestInput = {
    object: signedManifest,
    expected_object_id: workspaceObjectId(signedManifest),
    keri_authoritative: true,
    repository_reachable: true,
  };
  const authorization = {
    requested: ["read", "write"],
    workspace_ceiling: ["read", "write", "admin"],
    role_path_ceilings: [["read", "write"], ["read", "write", "triage"]],
    subject_capabilities: ["read", "write"],
    device_active: true,
    denied: false,
    revoked: false,
    authority_conflict: false,
    carrier_only_evidence: false,
  };
  const grant = {
    actor_capabilities: ["admin", "invite"],
    grant_capabilities: ["read"],
    grant_delegable: false,
    required_approvals: 1,
    valid_approval_actors: ["actor-a"],
    subject_accepted: true,
    waiting_period_elapsed: true,
    invitation_nonce_unused: true,
    invitation_unexpired: true,
  };
  const allowance = {
    signatures_match: true,
    receiving_policy_allows: true,
    revoked: false,
    expired: false,
    requested_capabilities: ["read"],
    capability_ceiling: ["read", "triage"],
    proof_age: 300,
    proof_max_age: 300,
    grace_period: 600,
  };
  const inherited = [
    { host_id: "a", priority: 20, radicle_locators: ["rad:zA"], radicle_backed_relay: true },
    { host_id: "b", priority: 10, radicle_locators: ["rad:zB"], radicle_backed_relay: true },
  ];
  const keyRequest = {
    resource_known: true,
    host_authorized: true,
    device_active: true,
    membership_active: true,
    checkpoint_age: 300,
    requested_epoch: 4,
    current_epoch: 6,
    admission_epoch: 4,
    history_mode: "full" as const,
    selected_epochs: [] as number[],
  };
  const event = "{\"id\":\"same\",\"content\":\"ciphertext\"}";

  return [
    vector("workspace-object/001-canonical-valid.json", "workspace-object/canonical-valid",
      "A closed canonical Workspace manifest verifies its BIP-340 signature, KERI actor, repository binding, and object digest.",
      manifestInput, evaluateWorkspaceObject(manifestInput)),
    vector("workspace-object/002-unknown-member-rejected.json", "workspace-object/unknown-member-rejected",
      "An unknown member violates the closed Workspace object schema.",
      { ...manifestInput, object: { ...signedManifest, unknown: true } },
      evaluateWorkspaceObject({ ...manifestInput, object: { ...signedManifest, unknown: true } })),
    vector("workspace-object/003-signature-invalid.json", "workspace-object/signature-invalid",
      "A Workspace object with a mutated signature is rejected before policy.",
      { ...manifestInput, object: { ...signedManifest, signature: `00${String(signedManifest.signature).slice(2)}` } },
      evaluateWorkspaceObject({ ...manifestInput, object: { ...signedManifest, signature: `00${String(signedManifest.signature).slice(2)}` } })),

    vector("workspace-policy/001-intersection-valid.json", "workspace-policy/intersection-valid",
      "A request inside every workspace, role-path, subject, device, and resource ceiling is accepted.",
      authorization, evaluateAuthorization(authorization)),
    vector("workspace-policy/002-escalation-rejected.json", "workspace-policy/escalation-rejected",
      "A child role cannot widen the effective capability intersection.",
      { ...authorization, role_path_ceilings: [["read"]] }, evaluateAuthorization({ ...authorization, role_path_ceilings: [["read"]] })),
    vector("workspace-policy/003-denial-wins.json", "workspace-policy/denial-wins",
      "An explicit denial wins over otherwise valid authorization.",
      { ...authorization, denied: true }, evaluateAuthorization({ ...authorization, denied: true })),
    vector("workspace-policy/004-conflict-rejected.json", "workspace-policy/conflict-rejected",
      "Incomparable authority heads fail closed.",
      { ...authorization, authority_conflict: true }, evaluateAuthorization({ ...authorization, authority_conflict: true })),

    vector("workspace-grant/001-single-actor-active.json", "workspace-grant/single-actor-active",
      "An authorized inviter's routine grant activates after its required acceptance.",
      grant, evaluateGrantActivation(grant)),
    vector("workspace-grant/002-multi-approval-insufficient.json", "workspace-grant/multi-approval-insufficient",
      "A grant remains inactive until its distinct approval threshold is met.",
      { ...grant, required_approvals: 2 }, evaluateGrantActivation({ ...grant, required_approvals: 2 })),
    vector("workspace-grant/003-invite-replay-rejected.json", "workspace-grant/invite-replay-rejected",
      "A consumed one-time invitation nonce cannot activate another grant.",
      { ...grant, invitation_nonce_unused: false }, evaluateGrantActivation({ ...grant, invitation_nonce_unused: false })),
    vector("workspace-grant/004-admin-no-governance.json", "workspace-grant/admin-no-governance",
      "Admin and invite capabilities do not imply policy governance.",
      { ...grant, grant_capabilities: ["govern-policy"] }, evaluateGrantActivation({ ...grant, grant_capabilities: ["govern-policy"] })),

    vector("workspace-relationship/001-bilateral-valid.json", "workspace-relationship/bilateral-valid",
      "Matching bilateral relationship signatures activate a bounded guest allowance.",
      allowance, evaluateAllowance(allowance)),
    vector("workspace-relationship/002-grace-boundary.json", "workspace-relationship/grace-boundary",
      "A previously current affiliation remains provisional at the exact signed grace boundary.",
      { ...allowance, proof_age: 900 }, evaluateAllowance({ ...allowance, proof_age: 900 })),
    vector("workspace-relationship/003-stale-rejected.json", "workspace-relationship/stale-rejected",
      "An affiliation proof one second beyond proof plus grace is suspended.",
      { ...allowance, proof_age: 901 }, evaluateAllowance({ ...allowance, proof_age: 901 })),
    vector("workspace-relationship/004-mismatched-signatures.json", "workspace-relationship/mismatched-signatures",
      "One-sided or mismatched relationship bytes do not activate an allowance.",
      { ...allowance, signatures_match: false }, evaluateAllowance({ ...allowance, signatures_match: false })),

    vector("workspace-privacy/001-public-clean.json", "workspace-privacy/public-clean",
      "A public directory with no concealed correlations is valid.",
      { private_identifiers: [], private_counts: 0, encrypted_placeholders: 0 },
      evaluatePrivateProjection({ private_identifiers: [], private_counts: 0, encrypted_placeholders: 0 })),
    vector("workspace-privacy/002-concealed-correlation-rejected.json", "workspace-privacy/concealed-correlation-rejected",
      "A public stable digest or identifier for a private role is rejected.",
      { private_identifiers: [H64], private_counts: 0, encrypted_placeholders: 0 },
      evaluatePrivateProjection({ private_identifiers: [H64], private_counts: 0, encrypted_placeholders: 0 })),

    vector("workspace-host/001-inherited-failover.json", "workspace-host/inherited-failover",
      "The last responsive eligible inherited host is tried before the remaining deterministic order.",
      { inherited, mode: "default", configured: [], last_responsive: "a" },
      resolveEffectiveHosts({ inherited, mode: "default", configured: [], last_responsive: "a" })),
    vector("workspace-host/002-replace-retains-backstop.json", "workspace-host/replace-retains-backstop",
      "A resource-specific replacement host is valid when it retains Radicle and relay backstop service.",
      { inherited, mode: "replace", configured: [inherited[1]], last_responsive: null },
      resolveEffectiveHosts({ inherited, mode: "replace", configured: [inherited[1]], last_responsive: null })),
    vector("workspace-host/003-no-backstop-rejected.json", "workspace-host/no-backstop-rejected",
      "An override cannot remove every Radicle-backed relay path.",
      { inherited, mode: "replace", configured: [{ host_id: "c", priority: 1, radicle_locators: [], radicle_backed_relay: false }], last_responsive: null },
      resolveEffectiveHosts({ inherited, mode: "replace", configured: [{ host_id: "c", priority: 1, radicle_locators: [], radicle_backed_relay: false }], last_responsive: null })),

    vector("workspace-device/001-independent-leaf-removal.json", "workspace-device/independent-leaf-removal",
      "Removing one device advances the role epoch without removing sibling leaves.",
      { persona_removed: false, removed_device: "d1", active_devices: ["d1", "d2"], current_epoch: 7 },
      evaluateRoleLeafChange({ persona_removed: false, removed_device: "d1", active_devices: ["d1", "d2"], current_epoch: 7 })),
    vector("workspace-device/002-persona-removes-all-leaves.json", "workspace-device/persona-removes-all-leaves",
      "Removing a persona removes every device leaf and advances the role epoch once.",
      { persona_removed: true, removed_device: null, active_devices: ["d1", "d2"], current_epoch: 7 },
      evaluateRoleLeafChange({ persona_removed: true, removed_device: null, active_devices: ["d1", "d2"], current_epoch: 7 })),

    vector("workspace-key/001-full-history.json", "workspace-key/full-history",
      "Full-history policy returns an idempotent device-bound historical key envelope.",
      keyRequest, evaluateKeyRequest(keyRequest)),
    vector("workspace-key/002-from-admission-denied.json", "workspace-key/from-admission-denied",
      "From-admission policy denies a pre-admission resource epoch.",
      { ...keyRequest, history_mode: "from-admission", requested_epoch: 3 },
      evaluateKeyRequest({ ...keyRequest, history_mode: "from-admission", requested_epoch: 3 })),
    vector("workspace-key/003-selected-snapshot.json", "workspace-key/selected-snapshot",
      "Selected-snapshot policy releases only an explicitly selected earlier epoch.",
      { ...keyRequest, history_mode: "selected-snapshots", requested_epoch: 3, selected_epochs: [3] },
      evaluateKeyRequest({ ...keyRequest, history_mode: "selected-snapshots", requested_epoch: 3, selected_epochs: [3] })),
    vector("workspace-key/004-unauthorized-host.json", "workspace-key/unauthorized-host",
      "A host outside the resource checkpoint custody set cannot return an envelope.",
      { ...keyRequest, host_authorized: false }, evaluateKeyRequest({ ...keyRequest, host_authorized: false })),
    vector("workspace-key/005-revoked-device.json", "workspace-key/revoked-device",
      "A revoked device cannot pull a current or historical resource key.",
      { ...keyRequest, device_active: false }, evaluateKeyRequest({ ...keyRequest, device_active: false })),
    vector("workspace-key/006-keypackage-readmission.json", "workspace-key/keypackage-readmission",
      "A currently authorized device missing the role epoch is re-admitted with a fresh KeyPackage before permitted keys are delivered.",
      { authorization_current: true, current_leaf_present: false, fresh_key_package_valid: true, history_mode: "from-admission" },
      { verdict: "accept", normalized: { action: "readmit-fresh-leaf", deliver_current_keys: true, deliver_pre_admission_keys: false } }),

    vector("workspace-freshness/001-ordinary-boundary.json", "workspace-freshness/ordinary-boundary",
      "An ordinary write is accepted at the exact 86400-second default boundary.",
      { operation_class: "ordinary", checkpoint_age: 86_400, policy_max_age: 86_400 },
      evaluateFreshness({ operation_class: "ordinary", checkpoint_age: 86_400, policy_max_age: 86_400 })),
    vector("workspace-freshness/002-ordinary-stale.json", "workspace-freshness/ordinary-stale",
      "An ordinary write one second beyond the 24-hour bound is stale.",
      { operation_class: "ordinary", checkpoint_age: 86_401, policy_max_age: 86_400 },
      evaluateFreshness({ operation_class: "ordinary", checkpoint_age: 86_401, policy_max_age: 86_400 })),
    vector("workspace-freshness/003-authority-boundary.json", "workspace-freshness/authority-boundary",
      "An authority mutation is accepted at the exact 300-second default boundary.",
      { operation_class: "authority", checkpoint_age: 300, policy_max_age: 300 },
      evaluateFreshness({ operation_class: "authority", checkpoint_age: 300, policy_max_age: 300 })),
    vector("workspace-freshness/004-authority-stale.json", "workspace-freshness/authority-stale",
      "An authority mutation one second beyond the five-minute bound is stale.",
      { operation_class: "authority", checkpoint_age: 301, policy_max_age: 300 },
      evaluateFreshness({ operation_class: "authority", checkpoint_age: 301, policy_max_age: 300 })),

    vector("workspace-joint/001-threshold-valid.json", "workspace-joint/threshold-valid",
      "A separate joint workspace identity accepts its own delegate threshold.",
      { independent_joint_identity: true, valid_distinct_delegates: 2, threshold: 2, host_signatures_counted: 0 },
      evaluateJointGovernance({ independent_joint_identity: true, valid_distinct_delegates: 2, threshold: 2, host_signatures_counted: 0 })),
    vector("workspace-joint/002-host-not-authority.json", "workspace-joint/host-not-authority",
      "A host signature cannot replace a missing joint-workspace delegate approval.",
      { independent_joint_identity: false, valid_distinct_delegates: 1, threshold: 2, host_signatures_counted: 1 },
      evaluateJointGovernance({ independent_joint_identity: false, valid_distinct_delegates: 1, threshold: 2, host_signatures_counted: 1 })),

    vector("workspace-events/001-mls-epoch-rotation.json", "workspace-events/mls-epoch-rotation",
      "A membership-changing MLS epoch selects a fresh event repository with one overlap locator.",
      { active_rid: "rad:zOld", active_mls_epoch: 7, current_mls_epoch: 8, size_bytes: 1, max_size_bytes: 5_000_000_000, next_rid: "rad:zNew" },
      selectEventRepository({ active_rid: "rad:zOld", active_mls_epoch: 7, current_mls_epoch: 8, size_bytes: 1, max_size_bytes: 5_000_000_000, next_rid: "rad:zNew" })),
    vector("workspace-events/002-size-rotation.json", "workspace-events/size-rotation",
      "The Comms repository-size boundary selects a fresh role event repository.",
      { active_rid: "rad:zOld", active_mls_epoch: 8, current_mls_epoch: 8, size_bytes: 5_000_000_000, max_size_bytes: 5_000_000_000, next_rid: "rad:zNew" },
      selectEventRepository({ active_rid: "rad:zOld", active_mls_epoch: 8, current_mls_epoch: 8, size_bytes: 5_000_000_000, max_size_bytes: 5_000_000_000, next_rid: "rad:zNew" })),
    vector("workspace-events/003-exact-bytes.json", "workspace-events/exact-bytes",
      "Direct Radicle ingestion and relay ingestion preserve the same exact Marmot event bytes.",
      { carriers: ["radicle-direct", "radicle-backed-relay"], events: [event, event] },
      eventsAreByteIdentical([event, event])),
    vector("workspace-events/004-mutated-bytes-rejected.json", "workspace-events/mutated-bytes-rejected",
      "Whitespace or other byte mutation across carriers is not semantic equivalence.",
      { carriers: ["radicle-direct", "radicle-backed-relay"], events: [event, `${event} `] },
      eventsAreByteIdentical([event, `${event} `])),
    vector("workspace-events/005-nostr-radicle-equivalent.json", "workspace-events/nostr-radicle-equivalent",
      "Optional standard Nostr, direct Radicle, and Radicle-backed relay delivery converge on identical signed bytes.",
      { carriers: ["nostr", "radicle-direct", "radicle-backed-relay"], events: [event, event, event] },
      eventsAreByteIdentical([event, event, event])),
  ];
}
