import { mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, sep } from "node:path";
import { authorAllVectors } from "./author.js";
import { buildCoverage, writeCoverage } from "./coverage.js";
import { validateVectorOrThrow } from "./schema.js";
import type { Vector } from "./types.js";

export type VerifyResult = {
  validFiles: number;
  errors: string[];
};

export async function verifyVectorTree(rootDir: string): Promise<VerifyResult> {
  const errors: string[] = [];
  const vectorFiles = await listVectorFiles(rootDir);
  const committedVectors: Vector[] = [];

  for (const file of vectorFiles) {
    try {
      const value = JSON.parse(await readFile(join(rootDir, file), "utf8")) as unknown;
      validateVectorOrThrow(value);
      committedVectors.push(value);
    } catch (error) {
      errors.push(`${file}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  const tempDir = await mkdtemp(join(tmpdir(), "heterodyne-vector-regen-"));
  try {
    const generated = await authorAllVectors(tempDir);
    await writeCoverage(tempDir);
    const generatedSet = new Set(generated);
    for (const file of vectorFiles) {
      if (!generatedSet.has(file)) errors.push(`${file}: unexpected committed vector`);
    }
    const committedSet = new Set(vectorFiles);
    for (const file of generated) {
      if (!committedSet.has(file)) {
        errors.push(`${file}: missing committed vector`);
        continue;
      }
      const committedPath = join(rootDir, file);
      const generatedPath = join(tempDir, file);
      try {
        const [committed, regenerated] = await Promise.all([
          readFile(committedPath, "utf8"),
          readFile(generatedPath, "utf8"),
        ]);
        if (committed !== regenerated) {
          errors.push(`${file}: regenerated bytes differ`);
        }
      } catch (error) {
        errors.push(`${file}: missing committed vector (${error instanceof Error ? error.message : String(error)})`);
      }
    }
    const projections = [
      "fixtures.json",
      "schema/vector.schema.json",
      "schema/reason-codes.json",
      "schema/reason-codes.md",
      "coverage/manifest.json",
      "coverage/core.md",
      "coverage/comms.md",
      "coverage/control.md",
      "coverage/social.md",
      "coverage/workspace.md",
      "coverage/family.md",
    ];
    for (const file of projections) {
      try {
        const [committed, regenerated] = await Promise.all([
          readFile(join(rootDir, file), "utf8"),
          readFile(join(tempDir, file), "utf8"),
        ]);
        if (committed !== regenerated) errors.push(`${file}: regenerated bytes differ`);
      } catch (error) {
        errors.push(`${file}: missing generated projection (${error instanceof Error ? error.message : String(error)})`);
      }
    }
    try {
      const manifest = JSON.parse(await readFile(join(rootDir, "coverage/manifest.json"), "utf8"));
      if (JSON.stringify(manifest) !== JSON.stringify(buildCoverage(committedVectors))) {
        errors.push("coverage/manifest.json: not the complete committed corpus projection");
      }
    } catch {
      // The projection read error above already reports this case.
    }
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }

  return {
    validFiles: vectorFiles.length,
    errors,
  };
}

async function listVectorFiles(rootDir: string): Promise<string[]> {
  const result: string[] = [];
  await walk(rootDir, result);
  return result
    .map((path) => relative(rootDir, path).split(sep).join("/"))
    .filter((path) => path.endsWith(".json"))
    .filter((path) => path !== "fixtures.json")
    .filter((path) => !path.startsWith("schema/"))
    .filter((path) => !path.startsWith("coverage/"))
    .filter((path) => !path.startsWith("generator/"))
    .sort();
}

async function walk(dir: string, result: string[]): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === ".git") {
        continue;
      }
      await walk(path, result);
    } else {
      result.push(path);
    }
  }
}
