import { mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, sep } from "node:path";
import { authorAllVectors } from "./author.js";
import { validateVectorOrThrow } from "./schema.js";

export type VerifyResult = {
  validFiles: number;
  errors: string[];
};

export async function verifyVectorTree(rootDir: string): Promise<VerifyResult> {
  const errors: string[] = [];
  const vectorFiles = await listVectorFiles(rootDir);

  for (const file of vectorFiles) {
    try {
      const value = JSON.parse(await readFile(join(rootDir, file), "utf8")) as unknown;
      validateVectorOrThrow(value);
    } catch (error) {
      errors.push(`${file}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  const tempDir = await mkdtemp(join(tmpdir(), "heterodyne-vector-regen-"));
  try {
    const generated = await authorAllVectors(tempDir);
    for (const file of generated) {
      const committedPath = join(rootDir, file);
      const generatedPath = join(tempDir, file);
      try {
        const [committed, regenerated] = await Promise.all([
          readFile(committedPath, "utf8"),
          readFile(generatedPath, "utf8"),
        ]);
        if (committed !== regenerated) {
          errors.push(`${file}: regenerated bytes differ`);
        }
      } catch (error) {
        errors.push(`${file}: missing committed vector (${error instanceof Error ? error.message : String(error)})`);
      }
    }
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }

  return {
    validFiles: vectorFiles.length,
    errors,
  };
}

async function listVectorFiles(rootDir: string): Promise<string[]> {
  const result: string[] = [];
  await walk(rootDir, result);
  return result
    .map((path) => relative(rootDir, path).split(sep).join("/"))
    .filter((path) => path.endsWith(".json"))
    .filter((path) => path !== "fixtures.json")
    .filter((path) => !path.startsWith("schema/"))
    .filter((path) => !path.startsWith("generator/"))
    .sort();
}

async function walk(dir: string, result: string[]): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === ".git") {
        continue;
      }
      await walk(path, result);
    } else {
      result.push(path);
    }
  }
}
