import { mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, sep } from "node:path";
import { authorAllVectors, packageSnapshot } from "./author.js";
import { buildCoverage, writeCoverage } from "./coverage.js";
import { validateVectorOrThrow } from "./schema.js";
import type { Vector } from "./types.js";
import {
  buildSnapshotManifest,
  loadSnapshotManifest,
  serializeSnapshotManifest,
} from "./snapshot-manifest.js";

export type VerifyResult = {
  validFiles: number;
  errors: string[];
};

export async function verifyVectorTree(rootDir: string): Promise<VerifyResult> {
  const errors: string[] = [];
  const vectorFiles = await listVectorFiles(rootDir);
  const committedVectors: Vector[] = [];

  for (const file of vectorFiles) {
    try {
      const value = JSON.parse(await readFile(join(rootDir, file), "utf8")) as unknown;
      validateVectorOrThrow(value);
      committedVectors.push(value);
    } catch (error) {
      errors.push(`${file}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  const tempDir = await mkdtemp(join(tmpdir(), "heterodyne-vector-regen-"));
  try {
    const generated = await authorAllVectors(tempDir);
    await writeCoverage(tempDir);
    const generatedSet = new Set(generated);
    for (const file of vectorFiles) {
      if (!generatedSet.has(file)) errors.push(`${file}: unexpected committed vector`);
    }
    const committedSet = new Set(vectorFiles);
    for (const file of generated) {
      if (!committedSet.has(file)) {
        errors.push(`${file}: missing committed vector`);
        continue;
      }
      const committedPath = join(rootDir, file);
      const generatedPath = join(tempDir, file);
      try {
        const [committed, regenerated] = await Promise.all([
          readFile(committedPath, "utf8"),
          readFile(generatedPath, "utf8"),
        ]);
        if (committed !== regenerated) {
          errors.push(`${file}: regenerated bytes differ`);
        }
      } catch (error) {
        errors.push(`${file}: missing committed vector (${error instanceof Error ? error.message : String(error)})`);
      }
    }
    const projections = [
      "fixtures.json",
      "schema/vector.schema.json",
      "schema/reason-codes.json",
      "schema/reason-codes.md",
      "coverage/manifest.json",
      "coverage/core.md",
      "coverage/assurance.md",
      "coverage/comms.md",
      "coverage/control.md",
      "coverage/social.md",
      "coverage/workspace.md",
      "coverage/family.md",
    ];
    for (const file of projections) {
      try {
        const [committed, regenerated] = await Promise.all([
          readFile(join(rootDir, file), "utf8"),
          readFile(join(tempDir, file), "utf8"),
        ]);
        if (committed !== regenerated) errors.push(`${file}: regenerated bytes differ`);
      } catch (error) {
        errors.push(`${file}: missing generated projection (${error instanceof Error ? error.message : String(error)})`);
      }
    }
    try {
      const manifest = JSON.parse(await readFile(join(rootDir, "coverage/manifest.json"), "utf8"));
      if (JSON.stringify(manifest) !== JSON.stringify(buildCoverage(committedVectors))) {
        errors.push("coverage/manifest.json: not the complete committed corpus projection");
      }
    } catch {
      // The projection read error above already reports this case.
    }
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }

  return {
    validFiles: vectorFiles.length,
    errors,
  };
}

export async function verifyPackagedSnapshot(
  expectedRoot: string,
  actualRoot: string,
): Promise<void> {
  const expectedVectorRoot = await pathExists(join(expectedRoot, "docs/spec/vectors"))
    ? join(expectedRoot, "docs/spec/vectors")
    : expectedRoot;
  const actualVectorRoot = await pathExists(join(actualRoot, "docs/spec/vectors"))
    ? join(actualRoot, "docs/spec/vectors")
    : actualRoot;
  const expectedManifestPath = join(expectedVectorRoot, "snapshot.json");
  if (await pathExists(expectedManifestPath)) {
    const actualManifest = loadSnapshotManifest(actualRoot);
    const expectedManifest = buildSnapshotManifest(expectedRoot, actualManifest.source_commit);
    const actualManifestBytes = await readFile(join(actualVectorRoot, "snapshot.json"), "utf8");
    if (actualManifestBytes !== serializeSnapshotManifest(expectedManifest)) {
      throw new Error("snapshot.json: regenerated bytes differ");
    }
    for (const artifact of expectedManifest.artifacts) {
      const relativePath = artifact.path.replace(/^docs\/spec\/vectors\//u, "");
      const [expected, actual] = await Promise.all([
        readFile(join(expectedVectorRoot, ...relativePath.split("/"))),
        readFile(join(actualVectorRoot, ...relativePath.split("/"))),
      ]);
      if (!expected.equals(actual)) throw new Error(`${relativePath}: regenerated bytes differ`);
    }
    return;
  }

  const expectedFiles = await listAllFiles(expectedVectorRoot);
  const actualFiles = await listAllFiles(actualVectorRoot);
  if (expectedFiles.join("\n") !== actualFiles.join("\n")) {
    throw new Error("packaged snapshot inventory differs");
  }
  for (const file of expectedFiles) {
    const [expected, actual] = await Promise.all([
      readFile(join(expectedVectorRoot, ...file.split("/"))),
      readFile(join(actualVectorRoot, ...file.split("/"))),
    ]);
    if (!expected.equals(actual)) throw new Error(`${file}: regenerated bytes differ`);
  }
}

export async function snapshotPackageCheck(
  rawRoot: string,
  snapshotRoot: string,
): Promise<void> {
  const manifest = loadSnapshotManifest(snapshotRoot);
  const stagingRoot = await mkdtemp(join(tmpdir(), "heterodyne-snapshot-package-check-"));
  try {
    await packageSnapshot(rawRoot, stagingRoot, manifest.source_commit);
    await verifyPackagedSnapshot(stagingRoot, snapshotRoot);
  } finally {
    await rm(stagingRoot, { recursive: true, force: true });
  }
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await readFile(path);
    return true;
  } catch (error) {
    const code = error !== null && typeof error === "object" && "code" in error
      ? error.code
      : undefined;
    if (code === "EISDIR") return true;
    if (code === "ENOENT") return false;
    throw error;
  }
}

async function listAllFiles(rootDir: string): Promise<string[]> {
  const result: string[] = [];
  await walk(rootDir, result);
  return result.map((path) => relative(rootDir, path).split(sep).join("/")).sort();
}

async function listVectorFiles(rootDir: string): Promise<string[]> {
  const result: string[] = [];
  await walk(rootDir, result);
  return result
    .map((path) => relative(rootDir, path).split(sep).join("/"))
    .filter((path) => path.endsWith(".json"))
    .filter((path) => path !== "fixtures.json")
    .filter((path) => !path.startsWith("schema/"))
    .filter((path) => !path.startsWith("coverage/"))
    .filter((path) => !path.startsWith("generator/"))
    .sort();
}

async function walk(dir: string, result: string[]): Promise<void> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === ".git") {
        continue;
      }
      await walk(path, result);
    } else {
      result.push(path);
    }
  }
}
